CREATE TABLE "EventGameRelations" (
	"BoardGameID" int8 NOT NULL,
	"BoardGameEventID" int8 NOT NULL,
	CONSTRAINT "PK_EventGameRelations" PRIMARY KEY ("BoardGameID", "BoardGameEventID")
);

ALTER TABLE public."EventGameRelations"
ADD CONSTRAINT "FK_EventGameRelations_Events_BoardGameEventID"
FOREIGN KEY ("BoardGameEventID") REFERENCES "Events"("ID") ON DELETE CASCADE;

ALTER TABLE public."EventGameRelations"
ADD CONSTRAINT "FK_EventGameRelations_Games_BoardGameID"
FOREIGN KEY ("BoardGameID") REFERENCES "Games"("ID") ON DELETE CASCADE;

CREATE TABLE "Events" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Title" text NOT NULL,
	"Date" date NOT NULL,
	"StartTime" time NOT NULL,
	"Duration" int8 NOT NULL,
	"Cost" int8 NOT NULL,
	"Purchase" bool NOT NULL,
	"OrganizerID" int8 NOT NULL,
	"VenueID" int8 NOT NULL,
	"Deleted" bool NOT NULL,
	"BeginRegistration" timestamp NOT NULL,
	"EndRegistration" timestamp NOT NULL,
	"Cancelled" bool NOT NULL DEFAULT false,0,
	CONSTRAINT "PK_Events" PRIMARY KEY ("ID")
);

ALTER TABLE public."Events"
ADD CONSTRAINT "FK_Events_Organizers_OrganizerID"
FOREIGN KEY ("OrganizerID") REFERENCES "Organizers"("ID") ON DELETE CASCADE;

ALTER TABLE public."Events"
ADD CONSTRAINT "FK_Events_Venues_VenueID"
FOREIGN KEY ("VenueID") REFERENCES "Venues"("ID") ON DELETE CASCADE;

CREATE TABLE "Favorites" (
	"BoardGameID" int8 NOT NULL,
	"PlayerID" int8 NOT NULL,
	CONSTRAINT "PK_Favorites" PRIMARY KEY ("BoardGameID", "PlayerID")
);

ALTER TABLE public."Favorites"
ADD CONSTRAINT "FK_Favorites_Games_BoardGameID"
FOREIGN KEY ("BoardGameID") REFERENCES "Games"("ID") ON DELETE CASCADE;

ALTER TABLE public."Favorites"
ADD CONSTRAINT "FK_Favorites_Players_PlayerID"
FOREIGN KEY ("PlayerID") REFERENCES "Players"("ID") ON DELETE CASCADE;

CREATE TABLE "Games" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Title" text NOT NULL,
	"Producer" text NULL,
	"Year" int8 NOT NULL,
	"MaxAge" int8 NOT NULL,
	"MinAge" int8 NOT NULL,
	"MaxPlayerNum" int8 NOT NULL,
	"MinPlayerNum" int8 NOT NULL,
	"MaxDuration" int8 NOT NULL,
	"MinDuration" int8 NOT NULL,
	"Deleted" bool NOT NULL,
	CONSTRAINT "PK_Games" PRIMARY KEY ("ID")
);

CREATE TABLE "Organizers" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" text NOT NULL,
	"Address" text NOT NULL,
	"Email" text NULL,
	"URL" text NULL,
	"PhoneNumber" text NULL,
	"Deleted" bool NOT NULL,
	CONSTRAINT "PK_Organizers" PRIMARY KEY ("ID")
);

CREATE TABLE "Players" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" text NOT NULL,
	"League" text NOT NULL,
	"Rating" int8 NOT NULL,
	"Deleted" bool NOT NULL,
	CONSTRAINT "PK_Players" PRIMARY KEY ("ID")
);

CREATE TABLE "Registrations" (
	"PlayerID" int8 NOT NULL,
	"BoardGameEventID" int8 NOT NULL,
	CONSTRAINT "PK_Registrations" PRIMARY KEY ("BoardGameEventID", "PlayerID")
);

ALTER TABLE public."Registrations"
ADD CONSTRAINT "FK_Registrations_Events_BoardGameEventID"
FOREIGN KEY ("BoardGameEventID") REFERENCES "Events"("ID") ON DELETE CASCADE;

ALTER TABLE public."Registrations"
ADD CONSTRAINT "FK_Registrations_Players_PlayerID"
FOREIGN KEY ("PlayerID") REFERENCES "Players"("ID") ON DELETE CASCADE;

CREATE TABLE "Roles" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"RoleName" text NOT NULL,
	"RoleID" int8 NOT NULL,
	"UserID" int8 NOT NULL,
	CONSTRAINT "PK_Roles" PRIMARY KEY ("ID")
);

ALTER TABLE public."Roles"
ADD CONSTRAINT "FK_Roles_Users_UserID"
FOREIGN KEY ("UserID") REFERENCES "Users"("ID") ON DELETE CASCADE;

CREATE TABLE "Users" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" text NOT NULL,
	"Password" text NOT NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("ID")
);

CREATE TABLE "Venues" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" text NOT NULL,
	"Type" text NOT NULL,
	"Address" text NOT NULL,
	"Email" text NULL,
	"URL" text NULL,
	"PhoneNumber" text NULL,
	"Deleted" bool NOT NULL,
	CONSTRAINT "PK_Venues" PRIMARY KEY ("ID")
);











