CREATE TABLE "Events" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Title" text NOT NULL,
	"Date" date NOT NULL,
	"StartTime" time NOT NULL,
	"Duration" int8 NOT NULL,
	"Cost" int8 NOT NULL,
	"Purchase" bool NOT NULL,
	"OrganizerID" int8 NOT NULL,
	"VenueID" int8 NOT NULL,
	"Deleted" bool NOT NULL,
	"BeginRegistration" timestamp NOT NULL,
	"EndRegistration" timestamp NOT NULL,
	"Cancelled" bool NOT NULL DEFAULT false,0,
	CONSTRAINT "PK_Events" PRIMARY KEY ("ID")
);

ALTER TABLE public."Events"
ADD CONSTRAINT "FK_Events_Organizers_OrganizerID"
FOREIGN KEY ("OrganizerID") REFERENCES "Organizers"("ID")
ON DELETE CASCADE;

ALTER TABLE public."Events"
ADD CONSTRAINT "FK_Events_Venues_VenueID"
FOREIGN KEY ("VenueID") REFERENCES "Venues"("ID")
ON DELETE CASCADE;
