CREATE TABLE "Games" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Title" text NOT NULL, "Producer" text NULL,
	"Year" int8 NOT NULL, "MaxAge" int8 NOT NULL,
	"MinAge" int8 NOT NULL, "MaxPlayerNum" int8 NOT NULL,
	"MinPlayerNum" int8 NOT NULL,
	"MaxDuration" int8 NOT NULL,
	"MinDuration" int8 NOT NULL,
	"Deleted" bool NOT NULL,
	CONSTRAINT "PK_Games" PRIMARY KEY ("ID"));
