CREATE TABLE "Organizers" (
	"ID" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" text NOT NULL,
	"Address" text NOT NULL,
	"Email" text NULL,
	"URL" text NULL,
	"PhoneNumber" text NULL,
	"Deleted" bool NOT NULL,
	CONSTRAINT "PK_Organizers" PRIMARY KEY ("ID")
);
